### ISSUE TITLE
FrozenError (can't modify frozen String) when using Ruby 2.5.0

### ISSUE THREAD

**Issue by edgarhenriquez** [mikel/mail#1209]
Hi, I'm using this gem (version 2.7.0) with Ruby 2.5.0 and this specific code (from the documentation):

```ruby
require 'mail'
Mail.defaults do
  retriever_method :pop3, :address    => 'host',
                          :port       => 995,
                          :user_name  => '<username>',
                          :password   => '<password>',
                          :enable_ssl => true
end
Mail.all
```

and I'm getting this error:

```
Traceback (most recent call last):
       16: from /Users/edgar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
       15: from /Users/edgar/.rbenv/versions/2.5.0/bin/irb:11:in `<top (required)>'
       14: from (irb):9
       13: from /Users/edgar/testing_mails/.bundle/gems/mail-2.7.0/lib/mail/mail.rb:164:in `all'
       12: from /Users/edgar/testing_mails/.bundle/gems/mail-2.7.0/lib/mail/network/retriever_methods/base.rb:42:in `all'
       11: from /Users/edgar/testing_mails/.bundle/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:63:in `find'
       10: from /Users/edgar/testing_mails/.bundle/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:135:in `start'
        9: from /Users/edgar/testing_mails/.bundle/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:83:in `block in find'
        8: from /Users/edgar/testing_mails/.bundle/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:83:in `each'
        7: from /Users/edgar/testing_mails/.bundle/gems/mail-2.7.0/lib/mail/network/retriever_methods/pop3.rb:84:in `block (2 levels) in find'
        6: from /Users/edgar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/pop.rb:807:in `pop'
        5: from /Users/edgar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/pop.rb:953:in `retr'
        4: from /Users/edgar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/pop.rb:1013:in `critical'
        3: from /Users/edgar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/pop.rb:955:in `block in retr'
        2: from /Users/edgar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/protocol.rb:276:in `each_message_chunk'
        1: from /Users/edgar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/pop.rb:808:in `block in pop'
FrozenError (can't modify frozen String)
```

It seems to be caused by [this change in Ruby 2.5.0](https://github.com/ruby/ruby/blob/ruby_2_5/lib/net/pop.rb#L1), breaking [this line](https://github.com/ruby/ruby/blob/ruby_2_5/lib/net/pop.rb#L808) in the `pop` method. Ideally, that line should be changed to something like `dest.dup` but I'm not familiar with the process to update/fix the std libs in Ruby.

So I'm fixing the error directly in this gem by changing the find method [here](https://github.com/mikel/mail/blob/9c3b17f0017d9a7cd77c51a8a9a93496885deae3/lib/mail/network/retriever_methods/pop3.rb#L76) and [here](https://github.com/mikel/mail/blob/9c3b17f0017d9a7cd77c51a8a9a93496885deae3/lib/mail/network/retriever_methods/pop3.rb#L84) and replacing the `mail.pop` call with `mail.pop(''.dup)`.

I could submit either a PR with this implementation if you like it or a different implementation if you have another solution in mind.

**Comment by jeremy** [comment]
Nice catch. It's a Ruby bug! https://bugs.ruby-lang.org/issues/14416

**Comment by aliuk2012** [comment]
Just an update looks like it will be fixed in Ruby 2.6 
https://github.com/ruby/ruby/commit/7830a950efa6d312e7c662beabaa0f8d7b4e0a23

**Comment by sungsong88** [comment]
I had exactly the same issue! (ruby 2.5.0)

I tried a couple different versions of ruby, and so far it worked on:

* 2.4.4
* 2.6.0-preview2

**Comment by kibotu21** [comment]
I have the same issue with ruby 2.5.1. is a fix available?

**Comment by drewish** [comment]
Per https://bugs.ruby-lang.org/issues/14416 it was backported to 2.5 last month. I'd expect it will be in the 2.5.2 release.

**Comment by charlie-hired** [comment]
2.5.3 fixed it
(maybe earlier too, but not tested)

**Comment by 13Ax0** [comment]
@charlie-hired Are you sure? Using 2.5.3 and still getting the error.

**Comment by charlie-hired** [comment]
> @charlie-hired Are you sure? Using 2.5.3 and still getting the error.

I was on 2.5.1p57 while wrote a small utility, then got this error. After upgrade to 2.5.3 it was gone (bundle upgraded, too)
Just double checked, and works (switched back to 2.5.1 and forth with rbenv)

**Comment by jasonswett** [comment]
Using Ruby 2.5.3 fixed it for me.
